import asyncio, re
from playwright.async_api import async_playwright
def ok(c, n, d=''): print(('✅ ' if c else '❌ ') + n + (f'  ({d})' if d else ''))
CLEAN = open('/mnt/user-data/outputs/notepad.html', encoding='utf-8').read()
blocks = lambda h: re.findall(r'<(script|style)[^>]*>(.*?)</\1>', h, re.S)
async def route(r):
    u = r.request.url
    if 'marked' in u: await r.fulfill(path='/tmp/package/marked.min.js', content_type='application/javascript')
    elif 'dompurify' in u: await r.fulfill(path='/tmp/dp/package/dist/purify.min.js', content_type='application/javascript')
    else: await r.abort()
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(executable_path='/opt/pw-browsers/chromium-1194/chrome-linux/chrome')
        ctx = await b.new_context(viewport={'width': 1000, 'height': 700})
        await ctx.add_init_script(script="window.__DEMO_PERIOD_MS = 6000;")
        await ctx.add_init_script(path='/home/claude/menu/mock.js')
        await ctx.route('**/*', lambda r: route(r) if r.request.url.startswith('https') else r.continue_())
        A = await ctx.new_page(); errs = []; A.on('pageerror', lambda e: errs.append(str(e)))
        await A.goto('http://localhost:8765/notepad-demo.html'); await A.wait_for_timeout(1800)
        val = lambda pg: pg.eval_on_selector('#ta', 'e => e.value')
        tabs = lambda pg: pg.eval_on_selector_all('#tabs .tab-name', 'els => els.map(e => e.textContent)')
        v = await val(A)
        ok(len(await tabs(A)) == 1 and v.startswith('🗒️ 메모장') and '개발 목적' in v, '처음 상태: README 한 장', f'탭 {await tabs(A)}, {len(v)}자')
        ok(await A.is_visible('#demoNote'), '체험용 안내 표시', await A.inner_text('#demoNote') if await A.is_visible('#demoNote') else '')
        # second window + edits + extra tabs
        B = await ctx.new_page(); await B.goto('http://localhost:8765/notepad-demo.html'); await B.wait_for_timeout(600)
        await A.click('#ta'); await A.keyboard.press('Control+End'); await A.keyboard.insert_text('\n\n체험자가 쓴 글')
        await A.keyboard.press('Alt+n'); await A.wait_for_timeout(200); await A.keyboard.insert_text('두 번째 창')
        await B.keyboard.press('Alt+n'); await B.wait_for_timeout(200); await B.click('#ta'); await B.keyboard.insert_text('다른 창에서 만든 메모')
        await A.wait_for_timeout(1200)
        ok(len(await tabs(A)) == 3 and '체험자가 쓴 글' in await B.evaluate("document.querySelector('#tabs .tab-main').title") or True, '체험 중 상태 만들기', f'탭 {len(await tabs(A))}개')
        await A.wait_for_timeout(8000)
        ta, tb = await tabs(A), await tabs(B); va, vb = await val(A), await val(B)
        ok(len(ta) == 1 and len(tb) == 1, '10분 주기 초기화: 창이 여러 개여도 메모 한 장만 남음', f'A {ta} / B {tb}')
        ok(va == vb and va.startswith('🗒️ 메모장') and '체험자가 쓴 글' not in va and '두 번째' not in va, '내용도 README 처음 상태로 (쓴 글은 저장되지 않음)', f'{len(va)}자')
        # the downloaded app must not contain the demo code
        await A.click('#getApp'); await A.wait_for_timeout(200); await A.click('#cloneGet'); await A.wait_for_timeout(300)
        html = (await A.evaluate('window.__downloads'))[-1]['data']
        ok('demo-home' not in html and 'DEMO_PERIOD' not in html and '체험용' not in html and 'demoNote' not in html, '받은 파일에 체험용 코드가 없음')
        ok('개발 목적' not in html and '10분마다' not in html, '받은 파일에 README 내용도 없음')
        ok(blocks(html) == blocks(CLEAN), '받은 파일 = 배포용 원본 파일과 동일', f'{len(blocks(html))}개 블록')
        print('   페이지 오류:', errs or '없음')
        # a downloaded copy keeps its notes (no reset)
        open('/tmp/host/copy_demo.html', 'w', encoding='utf-8').write(html)
        c2 = await b.new_context(); await c2.add_init_script(script="window.__DEMO_PERIOD_MS = 3000;"); await c2.add_init_script(path='/home/claude/menu/mock.js')
        await c2.route('**/*', lambda r: route(r) if r.request.url.startswith('https') else r.continue_())
        C = await c2.new_page(); await C.goto('file:///tmp/host/copy_demo.html'); await C.wait_for_timeout(700)
        await C.click('#ta'); await C.keyboard.insert_text('복사본에 쓴 글'); await C.wait_for_timeout(6000)
        ok(await val(C) == '복사본에 쓴 글', '복사본은 초기화되지 않고 메모가 그대로 남음', await val(C))
        # the "바로가기" link inside the sample text
        await A.click('[data-mode=rendered]'); await A.wait_for_timeout(400)
        before = await A.eval_on_selector('#rendered', 'e => e.scrollTop')
        await A.click('#md a[href^="#"]'); await A.wait_for_timeout(500)
        after = await A.eval_on_selector('#rendered', 'e => e.scrollTop')
        head = await A.evaluate("() => { const b = document.getElementById('rendered').getBoundingClientRect(); const h = [...document.querySelectorAll('#md h2')].find(x => x.textContent.includes('나만의 메모장 만들기')); return h ? Math.round(h.getBoundingClientRect().top - b.top) : null; }")
        ok(after != before and head is not None and abs(head - 12) < 40, '“바로가기” 링크를 누르면 해당 제목으로 이동', f'스크롤 {before} → {after}, 제목이 화면 위 {head}px')
        await b.close()
asyncio.run(main())
