import asyncio, re
from playwright.async_api import async_playwright
def ok(c, n, d=''): print(('✅ ' if c else '❌ ') + n + (f'  ({d})' if d else ''))
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(executable_path='/opt/pw-browsers/chromium-1194/chrome-linux/chrome')
        ctx = await b.new_context(); await ctx.add_init_script(path='/home/claude/menu/mock.js')
        await ctx.route('**/*', lambda r: r.abort() if r.request.url.startswith('https') else r.continue_())
        A = await ctx.new_page(); await A.goto('http://localhost:8765/notepad.html'); await A.wait_for_timeout(500)
        await A.click('#ta'); await A.keyboard.insert_text('사과 배 사과')
        st = lambda: A.evaluate("() => [!document.getElementById('findbar').hidden, !document.getElementById('replrow').hidden, document.activeElement.id]")
        print('── 1. 같은 단축키 두 번 → 닫힘')
        await A.keyboard.press('Control+f'); a = await st(); await A.keyboard.press('Control+f'); bb = await st()
        ok(a[:2] == [True, False] and bb[0] is False and bb[2] == 'ta', 'Ctrl+F 두 번', f'열림{a[:2]} → 닫힘, 커서는 편집기로')
        await A.keyboard.press('Control+h'); a = await st(); await A.keyboard.press('Control+h'); bb = await st()
        ok(a[:2] == [True, True] and bb[0] is False, 'Ctrl+H 두 번')
        await A.keyboard.press('Control+f'); await A.fill('#fq', '사과'); await A.keyboard.press('Control+f'); bb = await st()
        ok(bb[0] is False, '찾기 칸에 입력하던 중에 Ctrl+F → 닫힘')
        print('── 2. Ctrl+H를 켰다 끈 뒤 Ctrl+F')
        await A.keyboard.press('Control+h'); await A.keyboard.press('Control+h'); await A.keyboard.press('Control+f'); a = await st()
        ok(a[:2] == [True, False], 'Ctrl+H 두 번 → Ctrl+F', f'찾기창 {a[0]}, 바꾸기 줄 {a[1]}')
        await A.keyboard.press('Escape'); await A.keyboard.press('Control+h'); await A.keyboard.press('Escape'); await A.keyboard.press('Control+f'); a = await st()
        ok(a[:2] == [True, False], 'Ctrl+H → Esc → Ctrl+F', f'바꾸기 줄 {a[1]}')
        await A.click('#fclose'); await A.keyboard.press('Control+h'); await A.click('#fclose'); await A.keyboard.press('Control+f'); a = await st()
        ok(a[:2] == [True, False], 'Ctrl+H → 닫기 버튼 → Ctrl+F', f'바꾸기 줄 {a[1]}')
        await A.keyboard.press('Control+h'); a = await st(); ok(a[:2] == [True, True], '찾기 창이 열린 상태에서 Ctrl+H → 바꾸기 줄 추가')
        await A.keyboard.press('Control+f'); a = await st(); ok(a[:2] == [True, False], '바꾸기 창이 열린 상태에서 Ctrl+F → 찾기만 남음')
        await A.keyboard.press('Escape')
        print('── 바꾸기 펼치기/접기 버튼')
        await A.keyboard.press('Control+f'); await A.fill('#fq', '사과')
        tg = lambda: A.evaluate("() => { const t = document.getElementById('ftoggle'); const r = getComputedStyle(t.querySelector('.chev')).transform; return [t.getAttribute('aria-expanded'), !document.getElementById('replrow').hidden, r === 'none' ? '^' : 'v', t.title, document.activeElement.id]; }")
        a = await tg(); await A.click('#ftoggle'); await A.wait_for_timeout(250); bb = await tg(); await A.click('#ftoggle'); await A.wait_for_timeout(250); c = await tg()
        ok(a[:3] == ['false', False, '^'] and bb[:3] == ['true', True, 'v'] and c[:3] == ['false', False, '^'], '^ 누르면 v로 바뀌며 펼침, v 누르면 ^로 접힘', f'{a[2]}(접힘) → {bb[2]}(펼침) → {c[2]}(접힘)')
        ok(bb[4] == 'fr' and c[4] == 'fq', '펼치면 바꿀 내용 칸, 접으면 찾을 내용 칸으로 커서 이동')
        ok(a[3].startswith('바꾸기 펼치기') and bb[3].startswith('바꾸기 접기'), '버튼 설명 글이 상태에 맞게 바뀜', f'{a[3]} / {bb[3]}')
        await A.click('#ftoggle'); await A.fill('#fr', '배'); await A.click('#frep'); await A.wait_for_timeout(120)
        ok((await A.eval_on_selector('#ta', 'e => e.value')).count('사과') == 1 and await A.inner_text('#fcount') == '1/1', '펼친 뒤 바꾸기 동작 + 결과 수가 검색창 안에 표시', await A.inner_text('#fcount'))
        await A.click('#ftoggle'); await A.keyboard.press('Control+h'); a = await tg(); await A.keyboard.press('Control+h'); await A.keyboard.press('Control+f'); bb = await tg()
        ok(a[:3] == ['true', True, 'v'] and bb[:3] == ['false', False, '^'], 'Ctrl+H / Ctrl+F와 버튼 모양이 함께 맞춰짐')
        gap = await A.evaluate("() => document.getElementById('fprev').getBoundingClientRect().left - document.querySelector('.fq-wrap').getBoundingClientRect().right")
        ok(gap <= 6, '검색창과 ↑↓ 버튼 사이 여백 없앰', f'{gap:.0f}px')
        await A.keyboard.press('Escape')
        print('── 3. 저장 파일 이름')
        await A.click('.menu-btn:text-is("파일")'); await A.click('.menu-pop:not([hidden]) .mi:has-text("서식 제거 텍스트로 저장")'); await A.wait_for_timeout(150)
        await A.click('.menu-btn:text-is("파일")'); await A.click('.menu-pop:not([hidden]) .mi:has-text("마크다운 원본으로 저장")'); await A.wait_for_timeout(150)
        dl = await A.evaluate('window.__downloads'); now = await A.evaluate("(() => { const d = new Date(), p = x => String(x).padStart(2, '0'); return `${String(d.getFullYear()).slice(2)}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}`; })()")
        names = [d['filename'] for d in dl]
        ok(len(names) == 2 and re.fullmatch(r'\d{6}_\d{4}_메모\.txt', names[0]) and re.fullmatch(r'\d{6}_\d{4}_메모\.md', names[1]) and names[0].startswith(now), '파일 이름 "날짜_시간_메모"', ', '.join(names))
        await b.close()
        print('── 4. 다른 주소의 틀(iframe) 안에서 실행 (게시된 앱과 같은 구조)')
        b = await p.chromium.launch(executable_path='/opt/pw-browsers/chromium-1194/chrome-linux/chrome')
        ctx = await b.new_context(); await ctx.add_init_script(path='/home/claude/menu/mock.js')
        await ctx.route('**/*', lambda r: r.abort() if r.request.url.startswith('https') else r.continue_())
        P = await ctx.new_page(); await P.goto('http://localhost:8766/host.html'); await P.wait_for_timeout(800)
        F = P.frame_locator('#app'); fr = P.frames[1]
        await F.locator('#ta').click(); await P.keyboard.insert_text('앞')
        err = await fr.evaluate("Promise.race([navigator.clipboard.readText().then(() => '허용됨', e => e.name + ': ' + e.message), new Promise(r => setTimeout(() => r('응답 없음'), 3000))])")
        print('   브라우저 응답:', err)
        await F.locator('.menu-btn:text-is("편집")').click(); await F.locator('.menu-pop:not([hidden]) .mi:has-text("붙여넣기")').click(); await P.wait_for_timeout(400)
        ok(await F.locator('#ta').input_value() == '앞', '메뉴 붙여넣기는 막힘', '안내: ' + await F.locator('#toast').inner_text())
        await P.evaluate("navigator.clipboard && 0"); await F.locator('#ta').click(); await F.locator('#ta').press('End')
        await F.locator('#ta').evaluate("e => { const dt = new DataTransfer(); dt.setData('text/plain', '붙여넣은 글'); e.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true })); }")
        await b.close()
asyncio.run(main())
